name: app tests
on:
  push:
  pull_request:

jobs:
  running_tests:
    strategy:
      matrix: 
        os: [ ubuntu-latest ]
        python-version:
          - "3.7"
          - "3.8"
    name: TESTS
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: mongo-svc
      uses: art049/mongodb-cluster-action@v0

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run the application
      run: |
        cd app
        export FLASK_APP=main.py
        flask run &

    - name: Run Python tests
      run: pytest